---
# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_stages: [pre-commit]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9014
    hooks:
      - id: style-files
        name: Style code with `styler`
        args: [--style_pkg=styler, --style_fun=tidyverse_style, --cache-root=styler]
      - id: roxygenize
        name: Regenerate package documentation
        additional_dependencies:
          - bsicons
          - bslib
          - checkmate
          - commonmark
          - flextable
          - grid
          - gtsummary
          - knitr
          - lifecycle
          - R6
          - rlang
          - insightsengineering/rlistings # for rtables
          - rmarkdown
          - insightsengineering/rtables
          - insightsengineering/rtables.officer
          - davidgohel/officer # for rtables.officer
          - insightsengineering/formatters # for rtables
          - shiny
          - shinybusy
          - shinyjs
          - shinyWidgets
          - sortable
          - insightsengineering/teal.code
          - insightsengineering/teal.data
          - yaml
          - zip
      - id: spell-check
        name: Check spelling with `spelling`
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.css|
          .*\.jpg|
          .*\.js|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.Rds|
          .*\.rds|
          .*\.Rproj|
          .*\.sh|
          .*\.svg|
          .*\.xml|
          (.*/|)\_pkgdown.y[a]?ml|
          (.*/|)\.covrignore|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.y[a]?ml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)CODEOWNERS|
          (.*/|)DESCRIPTION|
          (.*/|)LICENSE|
          (.*/|)NAMESPACE|
          (.*/|)staged_dependencies\.y[a]?ml|
          (.*/|)WORDLIST|
          \.github/.*\.y[a]?ml|
          data/.*
          )$
      - id: no-browser-statement
        name: Check for browser() statement
