---
title: "Reporter Previewer"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple Reporter}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(shiny)
library(teal.reporter)
library(ggplot2)
library(dplyr)
library(rtables)
```

```{r}
ui <- fluidPage(
  titlePanel(""),
  tabsetPanel(
    tabPanel(
      "main App",
      tags$br(),
      tags$br(),
      sidebarLayout(
        uiOutput("encoding"),
        mainPanel(
          ### REPORTER
          teal.reporter::add_card_button_ui("addReportCard"),
          teal.reporter::download_report_button_ui("downloadButton"),
          teal.reporter::reset_report_button_ui("resetButton"),
          ###
          tags$br(),
          tags$br(),
          tabsetPanel(
            id = "tabs",
            tabPanel("Plot", plotOutput("dist_plot")),
            tabPanel("Table", verbatimTextOutput("table"))
          )
        )
      )
    ),
    tabPanel(
      "Previewer",
      reporter_previewer_ui("prev")
    )
  )
)

server <- function(input, output, session) {
  output$encoding <- renderUI({
    if (input$tabs == "Plot") {
      sidebarPanel(
        sliderInput(
          "binwidth",
          "binwidth",
          min = 2,
          max = 10,
          value = 8
        )
      )
    } else if (input$tabs == "Table") {
      sidebarPanel(
        selectInput(
          "stat",
          label = "Statistic",
          choices = c("mean", "median", "sd"),
          "mean"
        ),
      selectInput(
          "formats",
          label = "Format",
          choices = c("data.frame", "rtables"),
          "rtables"
        )
      )
    } else {
      NULL
    }
  })

  plot <- reactive({
    req(input$binwidth)
    x <- mtcars$mpg
    ggplot2::ggplot(data = mtcars, ggplot2::aes(x = mpg)) +
      ggplot2::geom_histogram(binwidth = input$binwidth)
  })

  output$dist_plot <- renderPlot({
    plot()
  })

  table <- reactive({
    req(input$stat)
    req(input$formats)

    lyt <- basic_table() %>%
      split_rows_by("Month", label_pos = "visible") %>%
      analyze("Ozone", afun = eval(str2expression(input$stat)))

    if (input$formats == "data.frame") {
      airquality %>% 
      group_by(Month) %>% 
      summarise_at(all_of("Ozone"),  get(input$stat), na.rm = TRUE)
    } else {
      build_table(lyt, airquality)
    }
  })

  output$table <- renderPrint({
    table()
  })

  ### REPORTER
  reporter <- teal.reporter::Reporter$new()
  card_fun <- function(card = ReportCard$new(), comment) {
    if (input$tabs == "Plot") {
      card$set_name("Plot Module")
      card$append_text("My plot", "header2")
      card$append_plot(plot())
      card$append_text("library(dplyr)\naa = airquality %>% mutate(Ozone3 = Ozone * 3)\naa", "verbatim")
    } else if (input$tabs == "Table") {
      card$set_name("Table Module")
      card$append_text("My Table", "header2")
      card$append_table(table())
      card$append_text("library(dplyr)\naa = airquality %>% mutate(Ozone2 = Ozone * 2)\naa", "verbatim")
    }
    card$append_text("Comment", "header3")
    card$append_text(comment)
    card
  }

  teal.reporter::add_card_button_srv("addReportCard", reporter = reporter, card_fun = card_fun)
  teal.reporter::download_report_button_srv("downloadButton", reporter = reporter)
  teal.reporter::reset_report_button_srv("resetButton", reporter)
  teal.reporter::reporter_previewer_srv("prev", reporter)
  ###
}

shinyApp(ui = ui, server = server)
```
